### PR TITLE
Fixed a grammar issue + restricted Mini TWOWs.

### LINKED ISSUE #10: Detect if only one minute and remove "s".

### PR DESCRIPTION
**Pull request by qixils**
This resolves https://github.com/demipixel/TWOWDiscordBot/issues/10 and restricts Mini TWOWs to a channel specified in the config.

### CODE REVIEW

**Comment by demipixel** [comment]
I'm a bit confused as to why it says every single line of the file was changed?

**Comment by qixils** [comment]
Honestly not sure, trying to figure that out myself..

EDIT: Seems to be because I directly uploaded the file to Github instead of using Github Desktop, will try to.. not do that for future commits

**Comment by demipixel** [comment]
1. Have you tested that it works?
2. Instead of putting the entire chat function around the if statement, maybe just return if it's not in the game channel?
3. Why did you use indexOf instead of ==? i.e. `if (gamesID != channelId) return;`
4. You should allow all channels with: `if (gamesID && gamesID != channelId) return;`

Otherwise it looks good :)

**Comment by qixils** [comment]
1. Yes, I have, I'm one of the few people (afaik) that have gotten the bot to run.
2. Done.
3. Whoops, fixed that (with your suggestion).
4. ^

**Comment by demipixel** [comment]
1. I was suggesting something like 

``` js
if (gamesID && gamesID != channelID) {
  chat(channelID, '<@'+userID+'>: This command only works in <#'+gamesID+'>.');
  return;
}
```

So you wouldn't need to have everything else indented (with the brackets). Also, I think there's an unnecessary `return` at the end of that function.

Okay, so I finally found your grammar changes (since it showed every file was changed :P) @ line 207 for you

Three things (first two are irrelevant)

A. You have `if (this.responseTimeTest = 60)` when I think you meant `if (this.responseTimeTest == 60)`.

B. You do `this.responseTimeTest = this.responseTime/60*100` but you only need to use `this.` if you're making it part of the object (and will need to use it sometime later). Instead, you should do `var responseTimeTest = this.responseTime/60*100`. However, I'm curious why you did `/60*100` because responseTime is already in seconds :P

C. (Relevant one): Typically it's considered bad programming practice to copy in paste code, especially if you're only changing one character! Instead, you might want to try add an in-line if like so:

``` js
this.chat('**Round '+this.round+'** prompt ('+this.getAlivePlayers(true).length+' players):\n**'+prompt+'**\n'+
 -       +                'You have '+Math.round(this.responseTime/60*100)/100+' minute'+(this.responseTime != 60 ? 's' : '')+'!\n'+
 -      const self = this;       +                'If you are a player, send me a private message: `!mini submit <response>`\n'+
 -      if (this.cleverBot && this.cleverBot.alive) {        +                'e.g. `!mini submit Anything relating to the prompt in ten words or fewer!`'); }
```

and remove the if statement around it.

**Comment by qixils** [comment]
Closing because never updated

**Pull request closed without merging**
